### PR TITLE
fix: links in API structure previews

### LINKED ISSUE #395: Links in API Structure Preview Are Broken
Screenshot 2023-03-23 at 9 47 16 PM

Note that the link URL (shown in bottom left corner) includes `.md`, and also duplicates `/latest/api/`.

### PR DESCRIPTION
**Pull request by dsanders11**
Fixes #395.

### CODE REVIEW

File: src/transformers/api-structure-previews.ts [hunk 1]
```diff
@@ -116,13 +150,21 @@ function replaceLinkWithPreview(node: Link | LinkReference) {
...
+          const previewNode = node as unknown as Literal<string>;
+          previewNode.type = 'jsx';
+          previewNode.value = `<APIStructurePreview url="${relativeStructureUrl}" title="${
+            (node.children[0] as Text | InlineCode).value
+          }" content="${encodeURIComponent(content)}"/>`;
+        })
+        .catch((err) => {
+          logger.error(err);
+          // NOTE - if build starts failing, comment the throw out
+          throw err;
```
Comment (dsanders11) [inline src/transformers/api-structure-previews.ts:165]: Opting to break loudly and break the build for the moment, otherwise we'll never notice an error being logged. If this becomes a problem we can re-evaluate.

**Review by erickzhao — APPROVED** [review]
